<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.7 on win32)" generated="20221003 08:52:48.143" rpa="false" schemaversion="3">
<suite id="s1" name="01-LoginTests" source="C:\Users\mateu\Downloads\agr_vai\TestCases\01-LoginTests.robot">
<test id="s1-t1" name="1 - Criar conta e fazer login" line="7">
<kw name="Dado que entro no site usando o navegador chrome" library="GlobalSteps" type="SETUP" sourcename="Dado que entro no site usando o navegador ${BROWSER}">
<kw name="Open Browser">
<arg>https://seubarriga.wcaquino.me/login</arg>
<arg>${BROWSER}</arg>
<msg timestamp="20221003 08:52:48.249" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20221003 08:52:48.249" endtime="20221003 08:52:48.249"/>
</kw>
<kw name="Maximize Browser Window">
<status status="NOT RUN" starttime="20221003 08:52:48.253" endtime="20221003 08:52:48.253"/>
</kw>
<status status="FAIL" starttime="20221003 08:52:48.246" endtime="20221003 08:52:48.254"/>
</kw>
<kw name="Fechar o navegador" library="GlobalSteps" type="TEARDOWN">
<kw name="Close Browser">
<msg timestamp="20221003 08:52:48.266" level="FAIL">No keyword with name 'Close Browser' found.</msg>
<status status="FAIL" starttime="20221003 08:52:48.266" endtime="20221003 08:52:48.266"/>
</kw>
<status status="FAIL" starttime="20221003 08:52:48.257" endtime="20221003 08:52:48.267">No keyword with name 'Close Browser' found.</status>
</kw>
<status status="FAIL" starttime="20221003 08:52:48.245" endtime="20221003 08:52:48.269">Setup failed:
No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.</status>
</test>
<status status="FAIL" starttime="20221003 08:52:48.146" endtime="20221003 08:52:48.281"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="01-LoginTests">01-LoginTests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221003 08:52:48.193" level="ERROR">Error in file 'C:\Users\mateu\Downloads\agr_vai\Steps\Global\GlobalSteps.robot' on line 3: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python310\Scripts\robot.exe
  C:\Python310\python310.zip
  C:\Python310\DLLs
  C:\Python310\lib
  C:\Python310
  C:\Python310\lib\site-packages</msg>
<msg timestamp="20221003 08:52:48.212" level="ERROR">Error in file 'C:\Users\mateu\Downloads\agr_vai\Steps\Home\HomeSteps.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python310\Scripts\robot.exe
  C:\Python310\python310.zip
  C:\Python310\DLLs
  C:\Python310\lib
  C:\Python310
  C:\Python310\lib\site-packages</msg>
<msg timestamp="20221003 08:52:48.223" level="ERROR">Error in file 'C:\Users\mateu\Downloads\agr_vai\Steps\Login\LoginSteps.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python310\Scripts\robot.exe
  C:\Python310\python310.zip
  C:\Python310\DLLs
  C:\Python310\lib
  C:\Python310
  C:\Python310\lib\site-packages</msg>
<msg timestamp="20221003 08:52:48.236" level="ERROR">Error in file 'C:\Users\mateu\Downloads\agr_vai\Steps\Bills\BillSteps.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python310\Scripts\robot.exe
  C:\Python310\python310.zip
  C:\Python310\DLLs
  C:\Python310\lib
  C:\Python310
  C:\Python310\lib\site-packages</msg>
</errors>
</robot>
